services:

  backend:
    build:
      context: ./backend
      dockerfile: Dockerfile
    image: urlshortener-backend
    command: uvicorn app.main:app --host 0.0.0.0 --port ${PORT} ${DEBUG:+--reload}
    env_file:
      - .env.dev
    volumes:
      - ./backend:/app
    ports:
      - "${PORT}:${PORT}"
    # environment:
    #   - DATABASE_URL=${DATABASE_URL}
    #   - CORS_ALLOWED_ORIGINS=${CORS_ALLOWED_ORIGINS}
    networks:
      - app-network
    # depends_on:
    #   - db

  frontend:
    build:
      context: ./frontend
      dockerfile: Dockerfile
    image: urlshortener_frontend
    env_file:
      - .env.dev
    volumes:
      - ./frontend:/app
      - /app/node_modules
    ports:
      - "{PORT_F1}:{PORT_F2}"
    networks:
      - app-network
    depends_on:
      - backend

  # db:
  #   image: postgres:17-alpine
  #   container_name: db
  #   volumes:
  #     - db_data:/var/lib/postgresql/data
  #   environment:
  #     - POSTGRES_DB=${POSTGRES_DB}
  #     - POSTGRES_USER=${POSTGRES_USER}
  #     - POSTGRES_PASSWORD=${POSTGRES_PASSWORD}

volumes:
  db_data:

networks:
  app-network:
    driver: bridge
