services:
  backend:
    build:
      context: ./backend
      dockerfile: Dockerfile
    # image: urlshortener-backend
    command: gunicorn backend.wsgi:application --bind 0.0.0.0:8000
    volumes:
      - ./backend:/app
    ports:
      - "8000:8000"
    environment:
      - DATABASE_URL=${DATABASE_URL}
      - CORS_ALLOWED_ORIGINS=http://localhost:3000,http://frontend:3000
    networks:
      - app-network
    depends_on:
      - db

  frontend:
    build:
      context: ./frontend
      dockerfile: Dockerfile
    # image: urlshortener_frontend
    volumes:
      - ./frontend:/app
      - /app/node_modules
    ports:
      - "3000:80"
    networks:
      - app-network
    depends_on:
      - backend

  db:
    image: postgres:17-alpine
    container_name: db
    volumes:
      - db_data:/var/lib/postgresql/data
    environment:
      - POSTGRES_DB=${POSTGRES_DB}
      - POSTGRES_USER=${POSTGRES_USER}
      - POSTGRES_PASSWORD=${POSTGRES_PASSWORD}

volumes:
  db_data:

networks:
  app-network:
    driver: bridge
