FROM python:3.13-slim

WORKDIR /app

COPY ../pyproject.toml ../uv.lock ./

RUN pip install uv
RUN uv install 

COPY ./app ./app

EXPOSE 8000

CMD ["uvicorn", "app.main:app", "--host", "0.0.0.0", "--port", "8000",]